require('dotenv').config({
    path:".env"
})

const SMS_KEY = process.env.SMS_KEY;
const EMAILJS_PUBLIC_KEY = process.env.EMAILJS_PUBLIC_KEY
const EMAILJS_PRIVATE_KEY = process.env.EMAILJS_PRIVATE_KEY
const EMAILJS_SERVICE_ID = process.env.EMAILJS_SERVICE_ID
const EMAILJS_TEMPLATE_ID = process.env.EMAILJS_TEMPLATE_ID

const FIREBASE_TYPE = process.env.FIREBASE_TYPE
const FIREBASE_PROJECT_ID = process.env.FIREBASE_PROJECT_ID
const FIREBASE_PRIVATE_KEY_ID = process.env.FIREBASE_PRIVATE_KEY_ID
const FIREBASE_PRIVATE_KEY = process.env.FIREBASE_PRIVATE_KEY
const FIREBASE_CLIENT_EMAIL = process.env.FIREBASE_CLIENT_EMAIL
const FIREBASE_CLIENT_ID = process.env.FIREBASE_CLIENT_ID
const FIREBASE_AUTH_URI = process.env.FIREBASE_AUTH_URI
const FIREBASE_TOKEN_URI = process.env.FIREBASE_TOKEN_URI
const FIREBASE_AUTH_PROVIDER_X509_CERT_URL = process.env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL
const FIREBASE_CLIENT_X509_CERT_URL = process.env.FIREBASE_CLIENT_X509_CERT_URL
const FIREBASE_CLIENT_UNIVERSE_DOMAIN = process.env.FIREBASE_CLIENT_UNIVERSE_DOMAIN
const FIREBASE_STORAGE_BUCKET = process.env.FIREBASE_STORAGE_BUCKET


module.exports = {
    SMS_KEY,
    EMAILJS_PRIVATE_KEY,
    EMAILJS_PUBLIC_KEY,
    EMAILJS_SERVICE_ID,
    EMAILJS_TEMPLATE_ID,

    FIREBASE_STORAGE_BUCKET,
    FIREBASE_TYPE,
    FIREBASE_PROJECT_ID,
    FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL,
    FIREBASE_CLIENT_ID,
    FIREBASE_AUTH_URI,
    FIREBASE_TOKEN_URI,
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
    FIREBASE_CLIENT_X509_CERT_URL,
    FIREBASE_CLIENT_UNIVERSE_DOMAIN,
    FIREBASE_PRIVATE_KEY_ID
}